apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: bazarr
spec:
  interval: 15m
  chart:
    spec:
      chart: bazarr
      version: 22.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            # nginx.ingress.kubernetes.io/auth-method: 'GET'
            # nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
            # nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
            # nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
          integrations:
            nginx:
              enabled: true
              auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_0}"
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
            homepage:
              enabled: true
              group: Arr Stack
              widget:
                enabled: false
          hosts:
            - host: bazarr.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    # service:
      # main:
      #   type: LoadBalancer
      #   loadBalancerIP: ${bazarr_IP}
      #   ports:
      #     main:
      #       port: 7878 # Default bazarr port
      #   annotations:
      #     kubectl.kubernetes.io/restartedAt: "2025-03-01T12:34:56Z"
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/playground/media
        mountPath: "/Media"
        server: 192.168.1.98


