---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 28.0.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: auth.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_KEY}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_KEY}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY}
    authelia:
      server:
        buffers:
          read: 16384
          write: 16384
      theme: auto
      totp:
        issuer: ${DOMAIN_0}
      authentication_backend:
        ldap:
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          tls:
            server_name: lldap.${DOMAIN_0}
          base_dn: "dc=homelab,dc=home"
          attributes:
            username: uid
          additional_users_dn: ou=people
          users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          user: uid=admin,ou=people,dc=homelab,dc=home
          password: ${LLDAP_PASSWORD}
      access_control:
        rules:
        - domain:
            - ${DOMAIN_0}
            - '*.${DOMAIN_0}'
          policy: two_factor
          subject:
            - 'group:admin'
      session:
        cookies:
          - domain: '${DOMAIN_0}'
            authelia_url: 'https://auth.${DOMAIN_0}'
            default_redirection_url: 'https://www.${DOMAIN_0}'
      regulation:
        find_time: 10m
        ban_time: 12h
      notifier:
        disable_startup_check: false
        filesystem:
          filename: '/config/notification.txt'