---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 28.0.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
        main:
          enabled: true
          ingressClassName: external
          annotations:
            "fluxcd.io/force-redeploy": "now"
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: auth.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_KEY}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_KEY}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY}
    persistence:
      config:
        enabled: false
      private-key:
        enabled: true
        mountPath: /opt/private.pem
        subPath: private.pem
        readOnly: true
        type: secret
        objectName: private-pem-secret
      configfile:
        enabled: true
        type: configmap
        objectName: authelia-configfile  
        expandObjectName: false
        mountPath: /configuration.yaml
        subPath: configuration.yaml
        readOnly: true
    secret:
      authelia-configfile:
        enabled: false
      private-pem-secret:
        enabled: true
        data:
          private.pem: |
            {{ genPrivateKey "rsa" | nindent 2 | trim }}
    
      