apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configfile
  namespace: authelia
data:
  configuration.yaml: |
    access_control:
      default_policy: 'deny'
      rules:
      - domain: "jellyfin.${DOMAIN_0}"
        resources:
          # public info & health
          # - '^/System/Info/Public$'
          - '^/[Ss]ystem/[Ii]nfo/[Pp]ublic$'
          - '^/Playback/BitrateTest$' 
          - '^/Streamyfin/config$'
          - '^/Users/AuthenticateByName'
          - '^/QuickConnect/Initiate'
          - '^/QuickConnect/Connect'
          - '^/Users/AuthenticateWithQuickConnect$'
          - '^/Sessions$'
          - '^/Items/Suggestions$'
          - '^/Shows/NextUp$'

          # - '^/system/info/public$'
          # - '^/System/Info/?$'
          # - '^/Ping$'
          # mobile login
          # - '^/Sessions/AuthenticateByName$'
          # - '^/Users/AuthenticateByName$'
          - '^/api/verify$'
        policy: bypass

      - domain: "jellyfin.${DOMAIN_0}"
        resources:
          - '^/sso/OID/redirect/authelia$'
          - '^/sso/OID/r/authelia$'
        policy: bypass
      # - domain: "jellyfin.${DOMAIN_0}"
      #   resources:
      #     - '^/Users/AuthenticateByName$'
      #     - '^/Sessions/AuthenticateByName$'
      #     - '^/System/Info/Public$'
      #     - '^/(api|sso)(/|$)'
        # policy: bypass
      - domain:
        - "abs.${DOMAIN_0}"
        - "jellyfin.${DOMAIN_0}"
        - "organizr.${DOMAIN_0}"
        policy: one_factor
        resources:
          - "^/.*$"
    identity_providers:
      oidc:
        clients:
          - client_id: ${JELLYFIN_OIDC_CLIENT_ID}
            client_name: 'Jellyfin'
            client_secret: ${JELLYFIN_OIDC_HASHED_CLIENT_SECRET}
            public: false
            authorization_policy: 'one_factor'
            require_pkce: true
            pkce_challenge_method: 'S256'
            redirect_uris:
              - 'https://jellyfin.${DOMAIN_0}/sso/OID/redirect/authelia'
              - 'https://jellyfin.${DOMAIN_0}/sso/OID/r/authelia'
              - 'https://jellyfin.${DOMAIN_0}/sso/OID/start/authelia'
            scopes:
              - 'openid'
              - 'profile'
              - 'groups'
            response_types:
              - 'code'
            grant_types:
              - 'authorization_code'
            consent_mode: implicit
            access_token_signed_response_alg: 'none'
            userinfo_signed_response_alg: 'none'
            token_endpoint_auth_method: 'client_secret_post'
