apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - authelia-configfile.configmap.yaml
  - authelia-oidc.secret.yaml
  # - jellyfin-oidc-config-backup.yaml
