apiVersion: v1
kind: ConfigMap
metadata:
    name: webfinger-config
    namespace: authelia
data:
    webfinger.json: ENC[AES256_GCM,data:g7bMRJtTLpNW698KiqFXa7rmylFEPj5ov/uipF1S9zv34OKDqeNY6R8/cRjaTqSnDSIgRAwQGF00mDvnee0vUZH5Ps9HCnhMk5YUOZCPP1Fikm4+mFRmGvQkb3GJTPOeKK1iWHjv/u9xerxVZfFODpB6j3J8SvCJzLkcQNHZbnP2WEb6+dfB0xqh4jmJ+8NSx/+GLJR5v5H2nEfITOeuUsmsWU49YLHIabZ0lqQA96BdhlUBr14lS2+9Edde,iv:CVLG72Q7g0rFY/Rf6OFJaILuuQ8XCwTaCOKMIxNsxvY=,tag:8NTNIpEbBsili7YU4eNsZQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TERzUTVNamdZenBHa1lu
            U2ltcnRNYW9RRmFGTndVMTlNanJhNHFTeEhBClcvZ080RUl2dXIxbkRpd09jamdC
            dkUrS3dxbUFMWi9jbjU5MTBtWUhmKzgKLS0tIGVYMC9kdkVFaVF0TjZFVzh1aXNY
            RzlXUzRKbVFWR05JUWVWNEsveVVxMm8KKdSjIVU4Wva/7SyFnCEh3oC3z80/SPGR
            AXj4Q4DV2BPUCTjRVrkozxH0Ep+yeEWWGT82qB+uDQbr6GObdtuJng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T15:23:25Z"
    mac: ENC[AES256_GCM,data:FS2uTknx9N7a7+gQGBmUp1u6xZKyjItFOLD0h/VwvjwO26fvqbY/BD4N7GC8zyW+wRQyrHyFlLmOhS4MpF5stcUkMPn9HE6p4pUNTT4oJs1DLcjxgCCSzlxk9ZhH5wfMNth0XaX5CaEmWqILQDpasIfrowdhkCFhFWPhNd3jl/A=,iv:3VdIhW4LAIveDSKYke7Vzm4EdbopKXZ2LXWoIhoyy70=,tag:Pufv6FhRkCGYYX54r0ZunQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
