apiVersion: v1
kind: ConfigMap
metadata:
    name: webfinger-config
    namespace: authelia
data:
    webfinger.json: ENC[AES256_GCM,data:PNv6ap7e+9HNxNtuNTwczA372sgtl6HsXMxRIYYObgFIbzyHrXzX46drsq3u/YH6QZNoG70rpTPXHyko0EvE88pUF0kl5AHAYazJuoooUbawk5X82NcDuWz3wcEcGDtj9kG7F7fyC/wJt3IkARkm3ACLiRXUIyCBFD7GaTA18E1Wrpdr45B2wuoLc0pUz0BqpFmXzADYcmhnY4qulwUK,iv:VrDi9BvHlvT1C2G+mpnHNBjVhDaahY2nnPeHY7W8Qzk=,tag:Hre/QmPhENS+JRBfmjkXnQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1tnmgqfexnqyx6paryj8rcw0yfxj4apz6hjl39zmkgykuxgt0s92s3eqedl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcW9HWlkydlREY1VPRUpN
            cGZBeEhrVzlGUjZmSDlOKzRZS25pZjhrU0hJCkRZUCtnMkl5TExCYnZ2enpoa2hq
            c2ZXSGhDY2NPNXpxOVpXK09OdHlPQlEKLS0tIGJyeDU4UlZIS1U2a0x2MzNvSzJS
            blJSU0lPQzY0YUZaRXJkS2FSTk1KRDQKC6hCFQh6BX0+eCByTzpdNrhtujF/hGK7
            ZodLmpmrE0yaMnHwJj0Z8h6+b/nwXzCmGySRhfJ46AXIrRIsy0LdWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T15:03:03Z"
    mac: ENC[AES256_GCM,data:xwFi31u4n4yIcgJoVRcVhf6Je9xx83xajMG2gb9kCT0eWd+Hy4x3Q2eGLW5Q2jmKycxuX3cvU6FNNJRx2O+9DQH931E5DAjQ1QpEkFLUSlBkIHUOZ1ODP8nx84qdZa5zMwCLVJbGSjq/0ZkAsZ5kJQddfy+ikDkNWAYGfgXFu5M=,iv:FmHON8CsiSfUgIu+gVyYtWRMOPceMph5AomHU3tUFc0=,tag:BONZiz1Gti52kpCk/Wm0Pw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
