---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 7.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # service:
    #   main:
    #     type: LoadBalancer
    #     loadBalancerIP: ${MEALIE_IP}
    #     ports:
    #       main:
    #         port: 389 
    global:
      stopAll: false
    ingress:
        main:
          ingressClassName: external
          enabled: true
          annotations:
            fluxcd.io/force-redeploy: "now"
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: lldap.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
                LLDAP_HTTP_URL: https://lldap.${DOMAIN_0}
                LLDAP_LDAP_BASE_DN: "dc=homelab,dc=home"
                LLDAP_LDAP_USER_DN: admin
                LLDAP_LDAP_USER_EMAIL: admin@${DOMAIN_0}
                LLDAP_LDAP_USER_PASS: ${LLDAP_PASSWORD}
                GID: 568
                UID: 568
                LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <${SMTP_USER}>
                LLDAP_SMTP_OPTIONS__PASSWORD: ${SMTP_PASSWORD}
                LLDAP_SMTP_OPTIONS__PORT: ${SMTP_PORT}
                LLDAP_SMTP_OPTIONS__REPLY_TO: Do not reply <${SMTP_USER}>
                LLDAP_SMTP_OPTIONS__SERVER: ${SMTP_HOST}
                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: ${SMTP_ENCRYPTION}
                LLDAP_SMTP_OPTIONS__USER: ${SMTP_USER}
                LLDAP_VERBOSE: true
                # LLDAP_key_file: /data/private_key
    # cnpg:
    #   main:
    #     annotations:
    #       cnpg.io/skipEmptyWalArchiveCheck: "enabled"
    #     mode: recovery
    #     cluster:
    #       singleNode: true
    #     backups:
    #       enabled: true
    #       credentials: minio
    #       scheduledBackups:
    #         - name: daily-backup
    #           schedule: "0 5 0 * * *"
    #           backupOwnerReference: self
    #           immediate: true
    #           suspend: false
    #     recovery:
    #       method: object_store
    #       credentials: minio

    # persistence:
    #   data:
    #     volsync:
    #       - name: data
    #         type: restic
    #         credentials: minio
    #         dest:
    #           enabled: true
    #         src:
    #           enabled: true
    #           trigger:
    #             schedule: 20 0 * * *