apiVersion: v1
kind: Pod
metadata:
  name: gluetun-formatter
  namespace: qbittorrent
spec:
  # force: true
  restartPolicy: Never
  securityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: gluetun
    image: qmcgaw/gluetun
    # command: ["format-servers", "-purevpn"]
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: false
      seccompProfile:
        type: RuntimeDefault
