apiVersion: batch/v1
kind: Job
metadata:
  name: gluetun-formatter
  namespace: qbittorrent
  annotations:
    reconcile.fluxcd.io/recreate: "true" 
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        command: ["gluetun", "format-servers", "-purevpn"]
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 0