apiVersion: batch/v1
kind: CronJob
metadata:
  name: gluetun-formatter
  namespace: qbittorrent
spec:
  schedule: "@daily"  # or "@hourly", "@reboot", etc.
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gluetun
            image: qmcgaw/gluetun
            command: ["/gluetun", "format-servers", "-purevpn"]
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                drop: ["ALL"]
              runAsNonRoot: false
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: Never