apiVersion: batch/v1
kind: Job
metadata:
  name: gluetun-formatter
  namespace: qbittorrent
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        command: ["gluetun", "format-servers", "-purevpn"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 0