apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: audiobookshelf
      version: 11.20.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      ingress:
        main:
          enabled: true
          ingressClassName: external
          annotations:
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
            homepage:
              enabled: true
              group: Tools
              widget:
                enabled: false
          hosts:
            - host: abs.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/playground/media
        mountPath: "/Media"
        server: 192.168.1.98

